### ISSUE TITLE
User experience: boolean questions could use default values

### ISSUE THREAD

**Issue by tyr431** [Diceycle/C-Hero-Calc#10]
Hey there, what do you think about default values for the yes/no questions?

Usually commandline tools offer them in order to speed up the workflow;
which would be handy considering repetitive questions like "Do you want to calculate another lineup?".

I would propose something like this [Y/n] like most [common linux tools](https://askubuntu.com/questions/322600/do-you-want-to-continuey-n-why-the-upper-case/322601) use.

This is not a "please write this", but a "Good reasons not to? Else I'll offer a solution."

**Comment by tyr431** [comment]
@Diceycle What do you think about it?

**Comment by Diceycle** [comment]
I already answered this in the game forum when someone else asked. In fact there is a fork maintained here https://github.com/LudoKressh/C-Hero-Calc that implements default anwswers for any query.

However, since you can code I recommend looking into using the macro files. That way you dont have to interact with the console at all

**Comment by tyr431** [comment]
Thanks.
I suppose you did not like the idea in the forum post?
